version: "2"
services:

  db:
    image: postgres:10.1-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

volumes:
  db-data: